language: cpp
os: linux
dist: focal
sudo: require
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-11
            - make
            - clang-format

before_script:
    - sudo ln -s /usr/bin/g++11 /usr/local/bin/g++
    - g++ -v

script:
    - make
