// this is an autogenerated file -- don't try to edit it!

#pragma once

#include <string>

using std::string;

const string __data_shader_sh_invert_vs = 
"#version 330\n"
"\n"
"in vec2 fragTexCoord;\n"
"in vec4 fragColor;\n"
"\n"
"uniform sampler2D texture0;\n"
"\n"
"out vec4 finalColor;\n"
"\n"
"void main() {\n"
"    vec4 texColor = texture(texture0, fragTexCoord);\n"
"\n"
"\n"
"    if (texColor.a < 0.51) {\n"
"      discard;\n"
"    }\n"
"\n"
"    //finalColor = mix(texColor, bgColor, vec4(0.5f));\n"
"    //texColor.rgb = vec3((texColor.r+texColor.g+texColor.b)/3.0f);\n"
"\n"
"    //texColor.rgb = mix(texColor.rgb, vec3(0,0,0), 2*distance(fragTexCoord, vec2(0.5, 0.5)));\n"
"    texColor.a = 1;//smoothstep(0.0f, 1.0f, texColor.a);\n"
"\n"
"    finalColor = texColor;\n"
"}\n"
"";

