#!/bin/zsh

# ALL CODEPOINTS DEFINED HERE

points=(
        "SYM_TREBLE,        0xE050" 
        "SYM_HEAD_WHOLE,    0xE0A2" 
        "SYM_NONE,          0x0000"
       )

echo "generating ${#points[@]} codepoints"
echo

echo "codepoints generated:"

spacelim=20

for i in $points; 
do
  for j in $(echo $i | tr "," "\n"):
  do

    line=$(echo $j | sed 's/://')
    if [ ${line:0:3} = "SYM" ]
    then
      echo -n $line
      #echo "size is: $(($spacelim-${#line}))"
      for k in $(seq 1 $(($spacelim-${#line})))
      do
        echo -n " "
      done
      echo -n "@ "
      #echo ${#line}
    else
      
      echo $line
    fi
  done
done

echo

#for i in $points; 
#do
  #echo $i
  #for j in $(echo $i | tr "," "\n"):
  #do

    #line=$(echo $j | sed 's/://')
    #echo $line
  #done
#done


# remove all previous headers
rm -f ./src/aghcp.h
rm -f ./src/aghcpenum.h

# overwrite file
# issue edit warning
echo "// this is an autogenerated file -- don't try to edit it!" > ./src/aghcp.h
echo "#ifndef AGHCP_H" >> ./src/aghcp.h
echo "#define AGHCP_H" >> ./src/aghcp.h
echo >> ./src/aghcp.h

echo "#include <vector>" >> ./src/aghcp.h
echo "" >> ./src/aghcp.h
echo "using std::vector;" >> ./src/aghcp.h
echo "" >> ./src/aghcp.h



echo "vector<int> codepointSet = {" >> ./src/aghcp.h

for i in $points; 
do
  for j in $(echo $i | tr "," "\n"):
  do
    line=$(echo $j | sed 's/://')
    if [ ${line:0:3} != "SYM" ]
    then
      echo -n "  " >> ./src/aghcp.h
      echo -n $line >> ./src/aghcp.h
      echo "," >> ./src/aghcp.h
    fi
  done
done

echo "};" >> ./src/aghcp.h

echo "" >> ./src/aghcp.h

echo "#endif //AGHCP_H" >> ./src/aghcp.h


# raw enums

echo "// this is an autogenerated file -- don't try to edit it!" > ./src/aghcpenum.h
echo "#ifndef AGHCPENUM_H" >> ./src/aghcpenum.h
echo "#define AGHCPENUM_H" >> ./src/aghcpenum.h
echo >> ./src/aghcpenum.h

echo "enum codepoints {" >> ./src/aghcpenum.h

for i in $points; 
do
  for j in $(echo $i | tr "," "\n"):
  do
    line=$(echo $j | sed 's/://')
    if [ ${line:0:3} = "SYM" ]
    then
      echo -n "  " >> ./src/aghcpenum.h
      echo -n $line >> ./src/aghcpenum.h
      echo -n " = " >> ./src/aghcpenum.h
    else
      echo -n $line >> ./src/aghcpenum.h
      echo "," >> ./src/aghcpenum.h
    fi
  done
done

echo "};" >> ./src/aghcpenum.h


echo "" >> ./src/aghcpenum.h

echo "#endif //AGHCPENUM_H" >> ./src/aghcpenum.h


# include both files in ./src/agh.h
#
#
echo "" >> ./src/agh.h
echo "#include \"aghcp.h\"" >> ./src/agh.h
echo "#include \"aghcpenum.h\"" >> ./src/agh.h
