// this is an autogenerated file -- don't try to edit it!

#pragma once

#include "agh/icon.h"
#include "agh/leland.h"
#include "agh/sh_fxaa.h"
#include "agh/sh_invert.h"
#include "agh/sh_ring.h"
#include "agh/sh_square.h"
#include "agh/sh_voronoi.h"
#include "agh/yklight.h"

#include "aghcp.h"
#include "aghcpenum.h"
