// this is an autogenerated file -- don't try to edit it!
#ifndef AGHCP_H
#define AGHCP_H

#include <vector>

using std::vector;

vector<int> codepointSet = {
  0xE000,
  0xE050,
  0xE062,
  0xE0A2,
  0x0000,
};

#endif //AGHCP_H
