// this is an autogenerated file -- don't try to edit it!
#ifndef AGHCPENUM_H
#define AGHCPENUM_H

enum codepoints {
  SYM_STAFF_BRACE = 0xE000,
  SYM_CLEF_TREBLE = 0xE050,
  SYM_CLEF_BASS = 0xE062,
  SYM_TIME_0 = 0xE080,
  SYM_TIME_1 = 0xE081,
  SYM_TIME_2 = 0xE082,
  SYM_TIME_3 = 0xE083,
  SYM_TIME_4 = 0xE084,
  SYM_TIME_5 = 0xE085,
  SYM_TIME_6 = 0xE086,
  SYM_TIME_7 = 0xE087,
  SYM_TIME_8 = 0xE088,
  SYM_TIME_9 = 0xE089,
  SYM_HEAD_WHOLE = 0xE0A2,
  SYM_ACC_FLAT = 0xE260,
  SYM_ACC_NATURAL = 0xE261,
  SYM_ACC_SHARP = 0xE262,
};

#endif //AGHCPENUM_H
