// this is an autogenerated file -- don't try to edit it!
#ifndef AGHCP_H
#define AGHCP_H

#include <vector>

using std::vector;

vector<int> codepointSet = {
  0xE000,
  0xE050,
  0xE062,
  0xE080,
  0xE081,
  0xE082,
  0xE083,
  0xE084,
  0xE085,
  0xE086,
  0xE087,
  0xE088,
  0xE089,
  0xE0A2,
  0xE260,
  0xE261,
  0xE262,
};

#endif //AGHCP_H
