// this is an autogenerated file -- don't try to edit it!
#ifndef AGHCPENUM_H
#define AGHCPENUM_H

enum codepoints {
  SYM_TREBLE = 0xE050,
  SYM_HEAD_WHOLE = 0xE0A2,
  SYM_NONE = 0x0000,
};

#endif //AGHCPENUM_H
