// this is an autogenerated file -- don't try to edit it!
#ifndef AGHFILE_H
#define AGHFILE_H

#include <vector>
#include "asset.h"

#define BUILD_DATE " "
#define COPY_YEAR " "

vector<asset> assetSet = {};
#endif //AGHFILE_H
